load cfg_save
% main_dir = 'C:\Projects\CQTdiffOFDM\notebooks\experiments\cqt\declipping04_01_2026\'
main_dir = 'C:\Projects\CQTdiffOFDM\notebooks\experiments\cqt\declipping06_01_2026_OFDM\'
out = wavs_to_ofdm_and_evm(cfg, ...
    [main_dir,'original\1.wav'], ...
    [main_dir,'clipped_10\1.wav'], ...
    [main_dir,'declipped_10\1.wav'], ...
    'Sync', false, ...
    'Plot', true);

    % ['C:\Users\owner\Documents\MATLAB\CQTdiff\2026-01-04\ofdm_maestro_like_Nfft2048_16QAM_clean.wav'], ...
